[package]
name = "proc_macros_learn_by_doing"
version = "0.1.0"
authors = ["fergal <fergaljamesoconnor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vectorize = { path = "vectorize" }
